### ISSUE TITLE
Remove partnership.redirector module from the project

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-webapps#17]
**Is your feature request related to a problem? Please describe.**
Since the partnership redirector module has been moved to the multiverse project, it is no longer related to this repository.

**Describe the solution you'd like**
Remove partnership.redirector module from the repository.
Remove the module from the pom.xml file

**Comment by Piumal1999** [comment]
I'll do it

**Comment by Piumal1999** [comment]
Done. PR #18

**Comment by jayasanka-sack** [comment]
Good job @Piumal1999 !
